//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPNRequest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Capabilities = new HashSet<Capability>();
        }
    
        public int Id { get; set; }
        public int EquipmentTypeId { get; set; }
        public int ContactId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual CSMApprovalStatu CSMApprovalStatu { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Status Status { get; set; }
        public virtual SIGApprovalStatu SIGApprovalStatu { get; set; }
        public virtual SQDNApprovalStatu SQDNApprovalStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capability> Capabilities { get; set; }
    }
}
