//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPNRequest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQDNApprovalStatu
    {
        public int RequestId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<int> DeniedBy { get; set; }
        public Nullable<System.DateTime> DeniedOn { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
