//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPNRequest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VPNRequestEntities : DbContext
    {
        public VPNRequestEntities()
            : base("name=VPNRequestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capability> Capabilities { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CSMApprovalStatu> CSMApprovalStatus { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SIGApprovalStatu> SIGApprovalStatus { get; set; }
        public virtual DbSet<SQDNApprovalStatu> SQDNApprovalStatus { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
